### ISSUE TITLE
Not all messages formatted properly

### ISSUE THREAD

**Issue by sumerman** [jonathanperret/logger_lager_backend#1]
Keep getting this in my logs:

`FORMAT ERROR: "~s" [[<<"GenServer :redis_sub_0_8 terminating">>,<<"\n** (stop) ">>|<<":redis_down">>]`

I guess you either have to change `~s` to `~p`, or (probably better) apply `iolist_to_binary` to the `message`

**Comment by jonathanperret** [comment]
Hi @sumerman, I got that too at first. At first I thought I would have to apply `iolist_to_binary` (or the Elixir wrapper, `IO.iodata_to_binary`), but that would be introducing another inefficiency into something that is already not very efficient. `~p` would not do because it would quote everything.

Turns out it's actually a recently fixed problem in `lager`: https://github.com/basho/lager/issues/326 so on my projects I just upgraded `lager` to the latest (3.2.0 includes the fix).

Do you think this would still be worth a mention in the `README` ?

**Comment by sumerman** [comment]
Thanks for the explanation!
